### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by present99** [cacophony-wj/LeS#13]
The Installation fails everytime, because it can not download from Loverslab. I do have a "Premium" account meaning I pay for it so Downloads work faster, It is also verified and works without a hitch... normaly. Is there a workaround? 
![bug](https://user-images.githubusercontent.com/69483317/89828013-ba742400-db58-11ea-948f-0978e408d701.PNG)

**Comment by deathking97** [comment]
You might need to download manually, check wabbajack logs in wabbajack installation folder (not modlists folders) then version of wabbajack 2.2. then logs then click the newest one or current that lists failed mods search on google for them. (i had trouble follow the links that comes with the logs saying "it doesn't exist") an place the mods into the modlist DOWNLOADS folder where you chose to place them when automatically starting the modlist from wabbajack. (You can use https://www.wabbajack.org/modlists/gallery then find the modlist in that list, click on ARCHIVE SEARCH for that modlist, this will also list the mods used and can open the link right to that mod for you to download)

**Comment by present99** [comment]
Thank you, this helps a lot :)

**Comment by present99** [comment]
Okay I downloaded all requested mods, yet the installation still does fail everytime due to 2 files that are IN the download folder and correct. at least one of them.
The Baka one is absolutly correct in version from Loverslab the other one does not exist anywere I could find it.
Help? I tried renaming the Billyy one, didn't work by removing the 1 at the end. I did copy both files in download just to be save and tried twice once with the unchanged in dowload and once with the changed.
![error](https://user-images.githubusercontent.com/69483317/90181064-27352b80-ddb0-11ea-8af1-e2ea3cf22b03.PNG)

**Comment by deathking97** [comment]
looks like billyy got updated

**Comment by deathking97** [comment]
never mind, you need 3,51 if your using the lastest version on the modlist (4,04)

**Comment by present99** [comment]
I feel like an Idiot asking this, but in the Readme is exactly this written
"BEFORE YOU CONTINUE:

The current list on Wabbajack is out of date. Grab the latest 4.0.4 from "Releases" ->"

But my problem here is... were ist this "releases'" to be found? I didn't find it anywere, am I blind?

Thx for your help :)

**Comment by deathking97** [comment]
![Untitled](https://user-images.githubusercontent.com/69437393/90188492-73ce3600-ddb3-11ea-9e69-dd6e29c56875.png)

**Comment by present99** [comment]
OMG... It was there all the time... okay okay this never happend, we dont speak of this... 👍 
THANK YOU MANY MANY TIMES I'll try this right now ^^

**Comment by present99** [comment]
I'm loosing hope here... just slightly...
One error still exists, but as you can see the file needed is in the download folder.
![baka](https://user-images.githubusercontent.com/69483317/90189566-b5fc7500-ddbd-11ea-9e72-67124468b999.PNG)

**Comment by cacophony-wj** [comment]
My apologies for my lack of responsiveness. There is no excuse. I still don't really have time to do a full update as my testing is not complete, but for now, you may have to do some things that seem rather weird. First, try moving ABC **out** of the downloads folder, closing and rerunning Wabbajack. Our magic may fix it. If that doesn't work, use the version from the main Wabbajack.exe program -- that one still works although a touch outdated. I can't remember which specific version it is though, there are so many.

**Comment by present99** [comment]
First of all Thank you for helping me :) You are excused, since life comes first always ;)
Secondly, I tried your way with Release 4.0.4 and 4.0.3.1 because these are the only ones that don't want Billyy's Animations to 3.5 since this file does no longer exist on Loverslab. As you might guess, it didn't work sadly :(
I guess I'll have to wait for an update unless you have another idea?

*in an ironic and funny note, error 404 file not found, the name for the newest version was well picked :D ;)

**Comment by present99** [comment]
I don't know what you did but the installation works now with version 4.1! Thank you!!!!! :)
