### ISSUE TITLE
CTD when on loading Main Menu

### ISSUE THREAD

**Issue by tigerboy985** [cacophony-wj/LeS#15]
**Describe the bug**
As soon as the main menu is loaded the game CTD's. I checked logs and I got this: 
More Informative Console
Initalizing
Establishing interfaces...
Reading in ini file
Plugin Initialization complete.

**What you were doing when the bug happened**
1. I loaded the game

**Is the bug repeatable**
No clue

**Expected behavior**
I should be able to continue my save

**Screenshots**

**Modlist version**
3.0

**Did you add any additional mods?**
Yes, but I already disabled them to see if it was the problem.
![image](https://user-images.githubusercontent.com/43861729/91227732-ec6fb380-e71e-11ea-8afa-647ba582260a.png)

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
This issue can be caused by several things that are usually specific to the PC you are using. Drop by Discord chat and drop a log file into it. I will look and see.

**Comment by NeroNightfire** [comment]
Thank you :)
