### ISSUE TITLE
Can't install due to Mega.NZ not found / broken link 

### ISSUE THREAD

**Issue by NeroNightfire** [cacophony-wj/LeS#16]
https://gyazo.com/8427a3371208de5624edbbf067d6b606

**Is the bug repeatable**
Clean install today and running Wabbajack, from menu selected LeS and ran it. See screen shot

**Comment by cacophony-wj** [comment]
You will have to refer to the manifest and download the file manually into your downloads folder. This manifest is available from http://www.wabbajack.org, find LeS and click on "archive search"
