### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by present99** [cacophony-wj/LeS#18]
In your newest build there are no genitals on the males just a hole. Restarting SOS made no difference and the "acts" aren't animated except for the sounds, maybe I didn't configured it right?

**Comment by cacophony-wj** [comment]
Prefer any pics be PG13 or lower. Reinstalling SOS can solve the missing members. For the animations, you have to be sure you disable the Devious ones or they'll just stand around.

**Comment by present99** [comment]
Sorry because of the picture, but it, in a way, was PG 13 ^^
Anyways re installing SOS helped and the animations work sometimes now.
Why are there no more Devious devices anymore? And FINIS is missing too? And some more '"exotic" things.  Not complaining here, it is a great gameplay with your mods, just wondering.

**Comment by cacophony-wj** [comment]
It is my preference not to include such mods. They end up bugging out so much I spend more time fixing bugs than I do playing when I test my own list. If I had the papyrus scripting knowledge to fix such bugs, I might enjoy the process more, but I don't. So I just removed them.
