### ISSUE TITLE
Wabbajack install failes on hash of Skyrim Realistic Overhaul 1.8 update

### ISSUE THREAD

**Issue by KodoShinobi** [cacophony-wj/LeS#19]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
Wabbajack install fails when checking the hash of Skyrim_Realistic_Overhaul_1.8._Update.rar. 

**What you were doing when the bug happened**
1. Install LeS for the firs time using Wabbajack
2. Skyrim_Realistic_Overhaul_1.8._Update.rar downloads successfully
3. hash runs and Install fails with attached message

**Is the bug repeatable**
Yes, it happens every time

****Troubleshooting steps taken****
1. Delete all downloaded files and try again - same result
2. rename Skyrim_Realistic_Overhaul_1.8._Update.rar and try again - same result
3. download Skyrim_Realistic_Overhaul_1.8._Update.rar independently and manually place it in the download folder - same result

**Expected behavior**
Expected behavior is for the install to succeed.

**Screenshots**
Attached

**Modlist version**
5.0 (not tested due to error from Rudy ENB update)
5.1 tested - error occurs
5.1.0.1 tested - error occurs

**Did you add any additional mods?**
No - clean install
Previously installed Living Skyrim - however, this was a clean install after removing Skyrim SSE, Living Skyrim, and using a new download directory, so there shouldn't be any conflict.
First attempt used the same download directory as Living Skyrim to reduce mod downloads.  Latter attempts used a clean empty directory.

**WARNING**
Understood
![SRO](https://user-images.githubusercontent.com/29106252/92456172-708e5600-f177-11ea-85d9-5e26b88c08a5.JPG)

**Comment by KodoShinobi** [comment]
Adding more screen shots.  Screen shot above was when using the master download directory.  These screenshots are from the new clean directory.
![SRO1](https://user-images.githubusercontent.com/29106252/92456938-691b7c80-f178-11ea-9e90-22fd5d3c1a7f.JPG)
![SRO2](https://user-images.githubusercontent.com/29106252/92457396-070f4700-f179-11ea-84f9-16b3dd409a53.JPG)
![SRO3](https://user-images.githubusercontent.com/29106252/92457422-0d9dbe80-f179-11ea-9e86-3fe615a386cd.JPG)

**Comment by KodoShinobi** [comment]
PS: Same result when attempting to download that file through a VPN to Europe, Asia, and North America to try and force the download from different mirrors.

**Comment by cacophony-wj** [comment]
I will push an update sometime today.

**Comment by KodoShinobi** [comment]
The good news is that Rudy's ENB for CW is updated and available again.

**Comment by cacophony-wj** [comment]
The list should be installable now. I just don't want to ping again.
