### ISSUE TITLE
Footstep Noises in Air After Sprinting and Jumping Forward

### ISSUE THREAD

**Issue by Space-Face** [cacophony-wj/LeS#20]
**Describe the bug**
While sprinting, if you jump, you can hear footsteps even though you are in the air. Does not happen in alternate start area, only once you leave.

**What you were doing when the bug happened**
1. Start sprinting.
2. Jump while holding forward.
3. Hear footsteps.

**Is the bug repeatable**
Yes

**Expected behavior**
No footstep noises while in the air after a sprinting jump forward.

**Screenshots**
N/A

**Modlist version**
5.1.0.2

**Did you add any additional mods?**
No

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
Thank you for your report. Does the effect happen with all armor sets, or just a few? Can you confirm what type of armor you were wearing? This will help me track down the error among the game's code.

**Comment by Space-Face** [comment]
Not a problem, thanks for looking into it! I tried a female start at the College of Winterhold where I first noticed. I had put on the Destruction robes you get from talking to the tour guide, took off mage hood, but kept the college boots I started with on since they were the same as the set you get from starting the tour. Then I tried a male start at the Solitude docks, I didn't check which armor I started with, but the problem showed up there as well. I just started messing around with the new version.

P.S. Separate Incident (small issue) - Not sure if this is an isolated incident, but the College tour guide when you first arrive (using College of Winterhold Guild start) took some odd routes to get to the dorms and back to the Main hall. She traveled through the midden (I think it's called) to the professor dorms, then to the roof of the college, then finally to the students dorms. Then took a similar path out.

**Comment by cacophony-wj** [comment]
I guess I'll have to check the navmeshes soon. I don't think I changed Winterhold in any way. Look up some of those Oblivion guard AI videos, it doesn't take a modder to fuck up people's walk pattern. :D

**Comment by Space-Face** [comment]
Lol no worries, it doesn't seem to be game breaking. Just thought I would mention it. Thanks!

**Comment by cacophony-wj** [comment]
After reading through the threads on Better Jumping (the mod that allows for sprint jumping) this appears to be a conflict between that mod and CGO (Combat Gameplay Overhaul). As I desire the features of both of these mods, I'm afraid this conflict will have to remain unresolved until someone more familiar with scripting writes a patch. Closed for now, but feel free to submit any other issues you may have.
