### ISSUE TITLE
Suggested Mods from Discord

### ISSUE THREAD

**Issue by ophaq** [cacophony-wj/LeS#21]
EDIT 1: Added Mods 11/25/2020

For lack of a suggestion section, I was told to put these here as a reminder. May edit this in the future if it doesn't get taken down. Some probably won't fit in because jankiness but may work if Loverlab / Sexlab mods which are known to cause incompatibilities / limitations (to my knowledge) could be moved and replaced for flowergirls and then further mods which couldn't be added due to those conflicts would be added. 

Suggestions with (?) are mods I know for sure may not fit in or be very buggy. Anyway, here they are:

realistic ragdolls and force
realistic armors
arctic frost effects redux
convenient horse
character behaviors enhanced
open cities?
fluffy cat ears ? (changes the top of models so models might need to be remade but totally worth it)
gr inari eartails ? (may change the top of models so models might need to be remade but totally worth it)
flowergirls
forgotten retex project
immersive citizens
immersive hud
osex?
realm of lorkhan?
relationship dialogue overhaul
rsse children
amazing follower
rudy hq falling leaves
rudy hq more lights arrows alt
rudy hq bthardamz
rudy hq chaurus eggs
rudy hq deathbells
rudy hq moths
rudy hq soulgems
rudy hq patch for rustic soulgems
skybirds
3d landscapes
3d trees and plants
smooth sky mesh
starsight eyes
immersive creatures
footprints
eyes of beauty elves edition?
the witcher eyes
unofficial material fix
cutting room floor
ultimate follower overhaul
verdant
wearable dragon horns and tail
wolfpaint
wards functionality extended
pretty animations? (multiple mod series that adds animations)
lakeview manor as it should be
magic casting animations overhaul
landscape fixes for grass mods
landscape fixes for gass mods immersive citizen patch
ecotone dual sheath
leanwolfs better shaped weapons
community overlays bodypaints warpaints
jk's skyrim
rustic noble furniture
girls heavy armors
realistic ai detection
master of disguise
suspicious guards
hiding spots
destructible display cases?
real flying? (to be used with any dragon wings mods)
immersive world encounters
js shrines of the divine
jk's arcadia cauldron
potion toxicity?
bleak falls barrow

----
Thanks for considering!

**Comment by cacophony-wj** [comment]
Thank you for your suggestions. I added RDO, GDO, OSex, FG, to either primary or alternate profiles in my alpha modlist Servitium. Feel free to check it out! Most of the others I can't use due to compatibility reasons as we discussed in #nsfw.
