### ISSUE TITLE
Werebeast Lock-up and Invisibility

### ISSUE THREAD

**Issue by Scarabim** [cacophony-wj/LeS#22]
**Describe the bug**
Upon transforming into a werebeast (whether through the Beast Form power or through Growl's forced transformation at night), a message appears in the top left corner of the screen saying "You can't continue fighting." I can't do anything, even the camera doesn't work quite right, only sliding up and down and maybe shifting left or right. My only option is to wait for the beast form timer to run out and force me back into regular form, at which point I can move again. I am not invincible during this portion, and can die very easily as a result. Initially, I was also completely invisible. There was just no model, either as a werewolf or a werebear. I installed new werebear meshes and textures from a mod, which fixed both problems as a werebear. However, it's suddenly come back and even though my transformed character is visible, I am just as immobile as initially. When it came back, ALL my save files became corrupted and could not be loaded; even new save files were corrupted. Restarting the game fixed them somehow, though, and that particular problem disappeared. 

**What you were doing when the bug happened**
1. Playing as a female Nord, able to transform into a werebear (selected through the Growl MCM) initially from either the Live Another Life start at Frostmoon Crag, or after drinking the beastblood during sleep; and later on with the perks Bestial Strength (2/4), Lycanthropic Speed, Lycanthropic Regeneration (1/2), Animal Vigor, and Supernatural Strength.
2. Location doesn't matter.
3. Fellow actors don't matter, and combat state doesn't matter either.
4. Press Z to activate the Beast Form power, or exit a cell into the nighttime and trigger a forced transformation.

**Is the bug repeatable**
Yes. It went away for a while after I installed new werebear meshes/textures (werewolf form was not fixed, just werebear), but it eventually came back (minus the invisibility) and is still repeatable.

**Expected behavior**
If there were no bug, I would be able to "continue fighting," and the werebeast forms would appear and act as normal.

**Screenshots**
Unfortunately, since Steam Overlay needs to be disabled for the modlist to work, I can't take screenshots. Hopefully these pictures I took with my phone work well enough. There was no way to get detailed info from the console.

[Upon transformation. Look at the upper left corner.](https://cdn.discordapp.com/attachments/719978982476611627/788587885351272469/IMG_20201215_210510.jpg)

[Idle "animation." Doesn't look very comfortable. The only thing I can move is the camera.](https://cdn.discordapp.com/attachments/719978982476611627/788587909359337472/IMG_20201215_210446.jpg)

**Modlist version**
6.0

**Did you add any additional mods?**
Yes, I have ONLY added Tamaska Werebear (a mesh and texture mod, but it contains a .esp flagged as an ESL for a female werebear mesh).

**WARNING**
_If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support._
There are two more things. Firstly, I am playing on a **brand new PC**, I just built it this past weekend. Fresh Windows install. I've downloaded the most recent Visual C++ Redistributable (2015, 2017, 2019) and .NET Framework (4.8), along with .NET Framework 3.5. The problem may very well be a buried requirement that is taken for granted by modders. Secondly, there is a warning in my Mod Organizer copy that suddenly appeared: "Script extender log reports incompatible plugins," specifically "EngineFixes.dll" which did not appear until a little while after installing the modlist. I have absolutely no idea how to fix that, or if that's what's causing the problem. As far as I can tell it's an unrelated issue, as I had that warning both while the werebeast bug was here and while it was gone.

**Comment by cacophony-wj** [comment]
Hello and welcome. These bugs are entirely due to misconfigurations on my part, but have mostly been addressed in the pins of the #licentia-support channel. Please enter that channel on Discord and type !pins to see them. If you don't want to do that, the basic process is to disable the Ashes mod within the MCM while suffering from lycanthropy (it's bugged and needs a fix) and also disable the ESP entitled "SeranaEditLocations.esp" somewhere in the load order in your right pane. I apologize for the inconvenience, thank you for commenting here at Github where others can see the issue, and feel free to stop by the Wabbajack Discord for further discussion and support. Have a great holiday!
