### ISSUE TITLE
Installation Error due to not being able to download USLEP Unpatch 104 from loverslab

### ISSUE THREAD

**Issue by ActuallyRyu** [cacophony-wj/LeS#29]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
Installation error due to not being able to download USLEP Unpatch 104 from loverslab

**What you were doing when the bug happened**
1. Download everything
2. Uslep Download error, cannot manually download it either cuz that certain version is no longer on loverslab
3. 
**Is the bug repeatable**
Yes

**Expected behavior**
Should be able to download

**Screenshots**
![image](https://user-images.githubusercontent.com/36943641/120112171-bfaf6780-c19a-11eb-803b-5fc123437488.png)

**Modlist version**
8.5.6.2

**Did you add any additional mods?**
No

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
The modlist is down presently for a serious crash bug. I will update when that is solved.
