### ISSUE TITLE
Static Skill Leveling won't let you choose a skill

### ISSUE THREAD

**Issue by AlcofribasN** [cacophony-wj/LeS#30]
**Describe the bug**
Can't use Static Skill Leveling. The prompt appears when I sleep but clicking on a skill does nothing. Seems to be because the mod prerequisites (Libfire and LibMathf) were missing. I installed them & it works fine now.

**Modlist version**
9.0 Alpha

**Did you add any additional mods?**
Window Shadows and Dynamic Volumetric Lighting and Sun Shadows.

**Comment by cacophony-wj** [comment]
Thank you very much for the heads up. This should be fixed in the latest unannounced update. Watch out for that save corruption bug!
