### ISSUE TITLE
Fails to hash file

### ISSUE THREAD

**Issue by Corbillion** [cacophony-wj/LeS#31]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
Wabbajack fails to hash file and installation ends

**What you were doing when the bug happened**
1.  I was running wabbajack and installing Licentia

**Is the bug repeatable**
Yes happens at the same place in the install every time

**Expected behavior**
The install would have continued past this point

**Screenshots**
Not an in game issue

**Modlist version**
9.5.3

**Did you add any additional mods?**
No
[Wabbajack.current.log](https://github.com/cacophony-wj/LeS/files/6720794/Wabbajack.current.log)

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
This has been resolved with an update to the modlist and an update to Wabbajack. Please run Wabbajack.exe from the main folder and allow it to update, then download the latest version of Licentia from the UI (gallery). Thank you.
