### ISSUE TITLE
startup problems

### ISSUE THREAD

**Issue by present99** [cacophony-wj/LeS#33]
**Describe the bug**
Always the standard startup, the famous wagon going into Helgen.

**What you were doing when the bug happened**
Freshly installed the mod according to what you've written. 

**Is the bug repeatable**
Everytime on every startup. Even thought there was a error with the last version so I waited for this new version, but still the same startup error

**Modlist version**
Current version on wabbajack 9.11.3.1

**Did you add any additional mods?**
Why change perfection?

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by present99** [comment]
I just noticed, no mod is loading at all... No other mod i tried, living Skyrim for example, had this problem. And yes I did re install the game according to your specifications before installing your mod

**Comment by cacophony-wj** [comment]
I'm afraid I don't know.
