### ISSUE TITLE
I crash everytime I open the inventory in some way. Started multiple new saves, whenever I open my inventory, or chests, or bodies I crash back to desktop. Easily repeatable on every save.

### ISSUE THREAD

**Issue by darkdragz6** [cacophony-wj/LeS#34]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
I crash everytime I open the inventory in some way. Started multiple new saves, whenever I open my inventory, or chests, or bodies I crash back to desktop. Easily repeatable on every save.

**What you were doing when the bug happened**
1. Start a new save or loaded a preexisting one 
2. opened any kind of inventory
3. Crashed to desktop

**Is the bug repeatable**
every time

**Expected behavior**
Open inventory with no crash

**Screenshots**
can't really

**Modlist version**
the latest

**Did you add any additional mods?**
nope

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
please attach a crash log if you can, they're in the overwrite folder

**Comment by cacophony-wj** [comment]
closed due to lack of response
