### ISSUE TITLE
(might be the wron section) is it Posible to reduce the esm+esp further for own addition

### ISSUE THREAD

**Issue by SHIIIZA117** [cacophony-wj/LeS#37]
for e.g. i want to add own clotheing replacer because i dont like "commen clothes, cloaks or Armor variants. "

i would like to replace them with own more suggestive additions.

also it would be nice to have more space to add my favorite quests.

best regards

**Comment by cacophony-wj** [comment]
Discussions of additions belong on my private server. Many options are available in the pins there, as well as by searching the channel for my modlist.
