### ISSUE TITLE
MCM Read Me Improvement

### ISSUE THREAD

**Issue by gardncol** [cacophony-wj/LeS#41]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
The MCM explanation for Fertility Mode +(FM+) has confusing language.  The non-unique men/women options are worded differently in the MCM, the explanation should reflect the verbiage used in the menu. It should read "Check _No Non-Unique Women_ and _No Non-Unique Men_"

**What you were doing when the bug happened**
Go to the LeS MCM read me.
Read through to the FM+ configuration section.
Look in MCM for FM+ settings.
Be confused.
Figure it out eventually.

**Is the bug repeatable**
Yes, as it is persistent in both FM+ MCM and the read me.

**Expected behavior**
For the readme to say: "Check _No Non-Unique Women_ and _No Non-Unique Men_"

**Modlist version**
10.10.1

**Did you add any additional mods?**
No.

**Comment by cacophony-wj** [comment]
fixed
