### ISSUE TITLE
armor texturing bug

### ISSUE THREAD

**Issue by sma342** [cacophony-wj/LeS#42]
**Describe the bug**
Finished the "Report to the Whiterun Jarl after Helgen events" quest and received "Ranger Armor". Decided to try it on and that's it.
Its hard to explain really, just check the screenshots

**What you were doing when the bug happened**
described in the description 

**Is the bug repeatable**
yes

**Expected behavior**
Well it shouldn't look like that

**Screenshots**
https://imgur.com/a/8uwI68B

**Modlist version**
10.10.1

**Did you add any additional mods?**
no, only removed minimap

**Comment by cacophony-wj** [comment]
I checked it and the mod is just ehhhh not the best. People tell me not to use Immersive Armors but ya cain't tell me nuthin'.
