### ISSUE TITLE
Problem installing Licentia - Unable to download certain files

### ISSUE THREAD

**Issue by SexyBeastLord** [cacophony-wj/LeS#43]
**Describe the bug**
Describe the bug as well as you can. Use precise language.

While trying to download and install Licentia I received these two errors.

Unable to download High_Poly_Herad_V1.4_(SE).zip (VectorPlexusOAuthDownloader+State/283/High_Poly_Head_V1.4_(SE).zip/False)

Unable to download BethINI Standalone Version-4875-3-5-1593829244.zip (NexusDownloader + State/Skyrim Special Edition/4875/148679)

At the top it said: Failed (9/22) Hashing Remaining
 Archives 868 of 868.

**What you were doing when the bug happened**

Downloading and Installing the game. with Wabberjack

**Is the bug repeatable**
If you go to the same place and do the same thing with the same stuff, does it happen again? If not, I may not be able to solve it. Yes or no will be enough.

I attempter it several times and it kept rehappening.

**Expected behavior**
Tell me what would have happened after step 3 above if everything were perfect for you.

The game would have been installed.

**Screenshots**

**Modlist version**
2.3.4.2

**Did you add any additional mods?**
No

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by SexyBeastLord** [comment]
**Describe the bug**
Describe the bug as well as you can. Use precise language.

While trying to download and install Licentia I received these two errors.

Unable to download High_Poly_Herad_V1.4_(SE).zip (VectorPlexusOAuthDownloader+State/283/High_Poly_Head_V1.4_(SE).zip/False)

Unable to download BethINI Standalone Version-4875-3-5-1593829244.zip (NexusDownloader + State/Skyrim Special Edition/4875/148679)

At the top it said: Failed (9/22) Hashing Remaining
 Archives 868 of 868.


**What you were doing when the bug happened**
Steps to reproduce the behavior:

Downloading and Installing the game. with Wabberjack



**Is the bug repeatable**
If you go to the same place and do the same thing with the same stuff, does it happen again? If not, I may not be able to solve it. Yes or no will be enough.

I attempter it several times and it kept rehappening.



**Expected behavior**
Tell me what would have happened after step 3 above if everything were perfect for you.

The game would have been installed.

**Screenshots**




**Modlist version**
2.3.4.2

**Did you add any additional mods?**
No

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
I'm sorry you experienced this issue. The Vector Plexus site is currently having technical difficulties. I imagine it will be resolved sometime today when everyone gets back into work. If you seek out the mod elsewhere please do not discuss it with myself or other support staff because technically it can only be given out by the author according to copyright. Thank you.
