### ISSUE TITLE
Weird blue lines and a red night sky

### ISSUE THREAD

**Issue by game4life2day** [cacophony-wj/LeS#46]
**Describe the bug**
It's tough to describe but there is weird blue wavy lines all over the place wherever light is shining. During the day the wavy blue lines are all over the sky and if there is a sun beam everything within the sun beam has the weird lines over it. During the night the entire sky looks like it has a grainy red overlay over the sky. Some of the npcs have the blue wavy texture on their neck when they are near a light source. 

**Screenshots**

![20211220114541_1](https://user-images.githubusercontent.com/96414186/146989224-771f98fe-e08c-43dd-9c05-d1186b7316e8.jpg)

![20211220114810_1](https://user-images.githubusercontent.com/96414186/146989243-858961f9-017c-4b93-8176-8a7b33f039af.jpg)

I took screenshots during the daytime also but for some reason the wavy lines don't show up in the screenshots.

**Modlist version**
3.0

**Did you add any additional mods?**
Yes, I went over to the licentia discord for help and was recommended to try the mod "Picta Series - Improved Sky Meshes".
I tried it but it didn't do anything so I uninstalled it. 
Besides that, I haven't downloaded any other mods.

**Comment by cacophony-wj** [comment]
I believe these are just certain elements of the weather. Wait around a couple days, see if it changes. If that doesn't work, try reinstalling the ENB according to the pins on my private server.
