### ISSUE TITLE
Incompatibility between Sunder and Wraithguard CC and LOTD

### ISSUE THREAD

**Issue by ThwartAbyss54** [cacophony-wj/LeS#47]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
There are two walls blocking access to and from the area and then the pedestal for the lexicon from Wraithguard cc overlaps the lift from LOTD terribly. You can click on the lift at least if you just move your cursor around till it pops up. The door in the back to the vault past the pedestal is completely covered by a wall from LOTD.
1. Go to the abandoned cave, the exit to the sightless pits, which is just on the cliff to the upper right when facing the sightless pits themselves.

**Is the bug repeatable**
I assume its the same on every profile?

**Screenshots**
![enb2022_1_4_06_03_38](https://user-images.githubusercontent.com/41197987/148144354-680f341b-e995-4c71-9cae-4a0cb7e2b343.jpg)
![enb2022_1_4_06_04_00](https://user-images.githubusercontent.com/41197987/148144373-1c3a04ec-6f02-4757-b00e-72108627823c.jpg)
![enb2022_1_4_06_10_50](https://user-images.githubusercontent.com/41197987/148144392-29246ec1-2b3a-4aa4-8088-579df6ed2b04.jpg)
![enb2022_1_4_17_44_53](https://user-images.githubusercontent.com/41197987/148144410-1cb7bdc9-0cd9-4004-814a-0db96f9b6ad9.jpg)

**Modlist version**
Licentia AE 10.18

**Did you add any additional mods?**
https://www.nexusmods.com/skyrimspecialedition/mods/50682

**Comment by cacophony-wj** [comment]
I used the Creation Kit to delete the overlapping objects. Both the lift and the lever are accessible now. Should be included in the next full AE release.
