### ISSUE TITLE
Kill / hit cams with bow are buggy / breaking the game

### ISSUE THREAD

**Issue by Lightningblade** [cacophony-wj/LeS#48]
**Describe the bug**
When using the bow you sometimes get into a cinematic scene. However this scene makes your character uncontrollable and sometimes takes 20-30 seconds where you can't do anything. It happens often, even if you miss or the target doesn't die. Since you can't control your character in this cinematic you often die. Sometimes not even an arrow is fired.

**What you were doing when the bug happened**
1. Shoot an bow in the direction of a low enemy

**Is the bug repeatable**
It is not really forcibly repeatable since I don't know the exact conditions for what triggers the cinematic but it happens extremely often.

**Expected behavior**
Either have it as the last hit on an enemy or disable it completely.

**Modlist version**
3.0 (Unsure, downloaded ~3 weeks ago)

**Did you add any additional mods?**
No

**Comment by Lightningblade** [comment]
I would like an option to disable the cinematics entirely

**Comment by cacophony-wj** [comment]
Yes, I have seen this, so in recent versions ranged killmoves are limited to the final hit on the final enemy. You can also fix it by opening the favorites menu and switching away from the bow. For your own version of the list, you can disable ranged killcams completely in the MCM for "VioLens." Just look around in there, I'm sure you'll find what you need.
