### ISSUE TITLE
mod removed from nexus

### ISSUE THREAD

**Issue by richrobber2** [cacophony-wj/LeS#55]
the mod [https://www.nexusmods.com/skyrimspecialedition/mods/49779] (artifacts of Skyrim - revised) was hidden on nexus thus it is no longer downloadable there so the mod list does not work anymore (at least I don't know how to get it working as I can't download the mod or find it elsewhere)

**Comment by NexusRegis** [comment]
You can for now download it from here and add it to the download path so it doesn't need to download it.

https://www.nexusmods.com/skyrimspecialedition/mods/49779?tab=files&file_id=227637
