### ISSUE TITLE
Missing Mods

### ISSUE THREAD

**Issue by Bubble-Lord** [cacophony-wj/LeS#59]
When I finished the download for the pack on Wabbajack it said there were three mods missing I was able to find two (Nchuak Default Normal Paths, and Artifacts of Skyrim) but I can not find Legacy of the Dragonborn patch-49779-1-2-0-1633451763

**Comment by Bubble-Lord** [comment]
nvm found that one too. It took a while though. I am not sure if I am allowed to share links or whatever but I am going to anyway.
Legacy of the Dragonborn patch-49779-1-2-0-1633451763: https://www.nexusmods.com/skyrimspecialedition/mods/49779?tab=files&file_id=232795

**Comment by damarcus220** [comment]
Hello, 
This modpack requires Markarth HD retexture https://www.nexusmods.com/skyrimspecialedition/mods/12326 which has since been deleted from nexus. Any help would be greatly appreciated.

**Comment by Dragnier** [comment]
Are you aware that [VectorPlexus](https://vectorplexus.com) is gone? https://twitter.com/VectorPlexus/status/988529948813078528

Not sure what mods in this list are from there, but you may want to add them as backup downloads somewhere.

**Comment by cacophony-wj** [comment]
Please refer to the readme for discussions of these issues.
