### ISSUE TITLE
(URGENT) Error while downloading the modlist

### ISSUE THREAD

**Issue by uzzarex** [cacophony-wj/LeS#62]
I cannot move to the installation process because of some kind of error during the downloading process.
Maybe, the problem is with servers, I dunno. Please help to solve this issue.

Skyrim version: Skyrim AE 1.6.353.0 (Steam) / all CC mods downloaded

Log:

570.41 - Downloading Data_ccQDRSSE001-SurvivalMode.esl
570.41 - Downloading Data_Dawnguard.esm
570.41 - Downloading Data_HearthFires.esm
570.41 - Downloading Data_Update.esm
570.41 - Downloading Data_Dragonborn.esm
570.41 - Downloading Data_ccBGSSSE025-AdvDSGS.esm
570.43 - Hashed download is incorrect
570.44 - Loading for alternative to P4vwTZ48vtU=
570.44 - No alternative for P4vwTZ48vtU= could be found
570.44 - Downloading Data_ccBGSSSE001-Fish.esm
570.45 - Hashed download is incorrect
570.45 - Loading for alternative to aSqpPvCAKbA=
570.45 - No alternative for aSqpPvCAKbA= could be found
570.48 - Hashed download is incorrect
570.48 - Loading for alternative to 2LsvJHFWOhg=
570.48 - No alternative for 2LsvJHFWOhg= could be found
570.51 - Hashed download is incorrect
570.51 - Loading for alternative to XlKELPX7jog=
570.51 - No alternative for XlKELPX7jog= could be found
570.8 - Hashed download is incorrect
570.8 - Loading for alternative to w7YJ2li+67E=
570.8 - No alternative for w7YJ2li+67E= could be found
570.92 - Hashed download is incorrect
570.92 - Loading for alternative to v593yGFgPDo=
570.92 - No alternative for v593yGFgPDo= could be found
571.41 - Hashed download is incorrect
571.41 - Loading for alternative to F76LaGyCAJA=
571.41 - No alternative for F76LaGyCAJA= could be found
571.45 - Hashing Remaining Archives
571.45 - Looking for files to hash
571.72 - Found 1739 total files, 1331 matching filesize
572.09 - Unable to download Data_ccBGSSSE001-Fish.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse001-fish.esm)
572.09 - Unable to download Data_ccBGSSSE025-AdvDSGS.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse025-advdsgs.esm)
572.09 - Unable to download Data_ccQDRSSE001-SurvivalMode.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccqdrsse001-survivalmode.esl)
572.09 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dawnguard.esm)
572.09 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dragonborn.esm)
572.09 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\hearthfires.esm)
572.09 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\update.esm)
572.09 - Cannot continue, was unable to download one or more archives

**Comment by uzzarex** [comment]
As the possible solution, can I get separately the links to the following mods:
1. Data_ccBGSSSE001-Fish.esm
2. Data_ccBGSSSE025-AdvDSGS.esm
3. Data_ccQDRSSE001-SurvivalMode.esl
4. Data_Dawnguard.esm
5. Data_Dragonborn.esm
6. Data_HearthFires.esm
7. Data_Update.esm

**Comment by uzzarex** [comment]
please help with my issue, i want to finish the installation, but it is not possible without the mentioned mods

**Comment by cacophony-wj** [comment]
Those are base game files. Please consult the readme. I will not provide further support on Github. You will have to join the Discord server to seek further assistance.
