### ISSUE TITLE
Crash on startup due to Bitdefender antivirus

### ISSUE THREAD

**Issue by mustapelto** [cacophony-wj/LeS#63]
**Problem:**
The (freshly installed, following all instructions incl. Anniversary Update stuff) game crashes on launch (briefly shows black screen with ENB text, then CTD) when Bitdefender Antivirus is running.

**Explanation:**
This seems to be a known problem with Bitdefender, as it is referenced (including a solution) on e.g. the Wildlander wiki. Apparently Bitdefender recognizes ModOrganizer and the "Stock Game" system's skyrimse.exe as "doing illegal stuff" and blocks their proper execution, preventing the game from loading completely and causing the CTD.

**Solution:**
Add an exception to "Advanced Threat Defense" for "[your Licentia folder]\stock game\skyrimse.exe" and to "Ransomware Remediation" for "[your Licentia folder]\modorganizer.exe".

Maybe this could be added to the installation guide?

**Comment by cacophony-wj** [comment]
Will do. I'll leave this issue open so others can see it.

**Comment by cacophony-wj** [comment]
Certainly, I will make a note of it.
