### ISSUE TITLE
Issue with Conjure Spectral Wolf Spellbook

### ISSUE THREAD

**Issue by ReturnToReason** [cacophony-wj/LeS#64]
**Describe the bug**
Text on the Conjure Spectral Wolf description when viewed from outside of ones inventory displays the description numerous times rather than once, leading to a wall of text.

**What you were doing when the bug happened**
1. I was in dried well
2. none
3. saw a book and looked at its description

**Is the bug repeatable**
Very

**Expected behavior**
description text would be seen once rather than multiple times

**Screenshots**
![Uploading image.png…]()

**Modlist version**
Packed 1.1

**Did you add any additional mods?**
None

**Comment by cacophony-wj** [comment]
The Conjure Spectral Wolf spell levels up along with your magic skill. The mod does not script itself to display only the abilities available at any given time, it shows all of them. I will try to research this.
