### ISSUE TITLE
DCL Robbery Quest Failed

### ISSUE THREAD

**Issue by MysticDaedra** [cacophony-wj/LeS#7]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
DCL Robbery quest fails even though you killed the thief and got your stuff back

**What you were doing when the bug happened**
1. Kill the thief
2. Immediately activate the corpse and loot all (R)
3. Several days later get "quest failed" notification

**Is the bug repeatable**
Most of the time

**Expected behavior**
Quest should complete normally

**Screenshots**
Uh, I'll try to remember next time it happens lol.

**Modlist version**
2.0.1.2

**Did you add any additional mods?**
Yes. Milk Mod Economy, Being A Cow, Forced Milkmaid, The Milk Maid

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support. **Gotcha. Definitely added stuff, also saw this bug _before_ I added the mods. I believe it to be a bug with DCL.**

**Comment by MysticDaedra** [comment]
Now the potential cause and fix: script lag. Every single time I waited a moment after killing the thief before looting my stuff, I got the Quest Complete notification. I suspect there is a script that runs after killing the thief, and if you loot your stuff too quickly, it'll not detect that you got your stuff back, and thus time out several in-game days later.

**Comment by cacophony-wj** [comment]
I will investigate on the forums and attempt to trigger the quest myself.

**Comment by cacophony-wj** [comment]
Oops.

**Comment by cacophony-wj** [comment]
Yep, this is most definitely broken and I would prefer not to fix it. Maybe it'll be fixed by the time Cursed Loot SE is out of Beta. Recommend you only use Defeat's manual surrender as per the updated README.md. I can't answer any more questions about SexLab-related death alternatives. Sorry. It's really too frustrating.
