### ISSUE TITLE
Eyes switching to vamp default after leaving Vampire Lord form

### ISSUE THREAD

**Issue by MysticDaedra** [cacophony-wj/LeS#8]
This template was stolen with minor adustments from erri120. Just type over the non-asterisked sections with your own words.

**Describe the bug**
**Exactly as title. After selecting a "new" custom color that I feel is appropriate for a vampire, but _isn't_ the default, it will switch back to the default every time you leave VL form.** 

**What you were doing when the bug happened**
**1. Change eye color from vamp default.
2. Activate Vampire Lord
3. Revert to human(oid) form.
4. Notice eye color is vamp default again, not chosen color.**

**Is the bug repeatable**
**Yes.**

**Expected behavior**
**I'd hope that my selected eye color would persist after being in Vampire Lord form for a while.** 

**Screenshots**
**It's default eye color, no console output showing anything useful or related.**

**Modlist version**
**2.0.1.2**

**Did you add any additional mods?**
**Yes: MME, BAC, Forced Milk Maid, The Milk Maid**

**WARNING**
If you waste my time pretending you didn't add stuff when you did or otherwise "neglecting" to mention things you know are causing problems, I will cease all support.

**Comment by cacophony-wj** [comment]
After research this appears to be a vanilla bug that has persisted through Dawnguard, referenced here:

http://www.gamesas.com/anyway-fix-the-stuck-eyecolor-vampires-t289535.html

However it is an 8 year old post and rather striking that the bug has not been addressed, but it may even be an "intended feature" as a consequence for becoming a vampire. As you saw above, it can be fixed but nobody has bothered to so. I have no interest in parsing the hundreds of records added to CGO to find the eye on each vampire race, but I will gladly patch yours if so desired.

**Comment by MysticDaedra** [comment]
I will look through the various bug fix mods and whatnot; if it is a vanilla bug, I'm actually very surprised that USLEEP or whatever it is called these days didn't fix it. Potentially an interaction between two different bug-fix mods? Not sure. Again, I'll troll through Nexus and see if I can't find something.

**Comment by cacophony-wj** [comment]
You never know about USSEP. Sometimes that team's decisions can be a bit arbitrary. I did some rudimentary searching for a mod to fix it but the general consensus seems to be that nobody has.

**Comment by Xalatesh** [comment]
Sry if this is a bit late, there is a mod called "True Hybrid - Tainted Blood of the Dragonborn" which has a function in it, which will let your vampire look like a normal human with eyes you want etc, didnt test it with vampire lord, but the eyes stay the same and dont go back to the Dawnguard eyes (even when you reload a save / restart the game)
