### ISSUE TITLE
Brynjolf voice and interaction becomes "..." after sex-bribe scene.

### ISSUE THREAD

**Issue by TheCatchyName** [cacophony-wj/LeS#9]
Brynjolf voice line on interaction becomes "..." after completing the sex-bribe attempt, during "a cornered rat" quest.

**What you were doing when the bug happened**
1. Be searching for Esbern, and not have completed "a chance arrangement"
2. Speak to Brynjolf to initiate his TG entrance quest.
3. Pick the option of (sex) to skip the entrance quest.
4. On completion of the sex scene, the player character falls to the floor in the bleedout struggle state, and all Brynjolf's lines are "..."

Repeated twice following the same procedure.

**Modlist version**
2.0.1.2

Additional mods added:
Complete Widescreen Fix
Silent Combat Music
Alternate Conversation Camera

**Comment by cacophony-wj** [comment]
Good, you are on 2.0.1.2 so I still have that installed. Attach your save files (two total) just before the bribe and I will see what I can do.

**Comment by TheCatchyName** [comment]
[brynjolfissue.zip](https://github.com/cacophony-wj/LeS/files/4991956/brynjolfissue.zip)

I noticed it also occurs when I do the sex bribe scene with the two thugs you first encounter in the ratway. Also, same thing happens to Lucien if I keep killing him while in bleedout state (eg when I accidentally hit with with Blood Scourge during combat, maybe you can try that out too)

**Comment by cacophony-wj** [comment]
Somehow a Defeat scenario is calling whenever you have a scene via SLSolutions. This suggests that the Defeat variables are screwy in some way. This may have happened if you once had any other mods installed or if you used Defeats "Clean and Reconfigure" options. If neither of those is the case, I am at a loss. Defeat is a very bad mod. I was able to continue your quest chain by shutting Defeat down **before** starting the scene. If you wish to continue this game, I suggest you do the same and use the "Combat Surrender" option within Cursed Loot.

**Comment by TheCatchyName** [comment]
Alright thanks for the tip. Will disable defeat. Besides, I'm late game enough that I hardly fall below 50% hp. Not to mention it's broken my poor lucien 3 times already.
